### ISSUE TITLE
Failing to compile with gcc 8.1

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/mavlink#903]
```
In function ‘void mav_array_memcpy(void*, const void*, size_t)’,
    inlined from ‘void mavlink_msg_named_value_float_send(mavlink_channel_t, uint32_t, const char*, float)’ at libraries/GCS_MAVLink/include/mavlink/v2.0/ardupilotmega/../common/./mavlink_msg_named_value_float.h:158:21,
    inlined from ‘void AP_Airspeed::read()’ at ../../libraries/AP_Airspeed/AP_Airspeed.cpp:404:43:
libraries/GCS_MAVLink/include/mavlink/v2.0/ardupilotmega/../protocol.h:176:9: error: ‘void* memcpy(void*, const void*, size_t)’ forming offset [5, 10] is out of the bounds [0, 4] [-Werror=array-bounds]
   memcpy(dest, src, n);
   ~~~~~~^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: some warnings being treated as errors

```

**Comment by patrickelectric** [comment]
It's working file with clang 6.0.0
