### ISSUE TITLE
Mavlink release/kinetic/mavlink no longer compatible with Mavros 1.2.0

### ISSUE THREAD

**Issue by marcelino-pensa** [mavlink/mavlink#1474]
I am cloning mavlink through `https://github.com/mavlink/mavlink-gbp-release.git` in the branch `release/kinetic/mavlink`. It seems like the most recent rebase from 7hrs ago prevents mavros `1.2.0` from compiling. Is this an intentional change?

This is the error:

```
Errors     << mavros:make /root/rosws/logs/mavros/build.make.000.log
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:70:40: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(mavlink::common::MAV_AUTOPILOT e);
                                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:68:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::MAV_SENSOR_ORIENTATION)’
 std::string to_string(mavlink::common::MAV_SENSOR_ORIENTATION e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:70:23: error: ‘MAV_AUTOPILOT’ is not a member of ‘mavlink::common’
 std::string to_string(mavlink::common::MAV_AUTOPILOT e);
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:70:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:34:12: note:   ‘mavlink::minimal::MAV_AUTOPILOT’
 enum class MAV_AUTOPILOT : uint8_t
            ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:71:40: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(mavlink::common::MAV_TYPE e);
                                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:68:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::MAV_SENSOR_ORIENTATION)’
 std::string to_string(mavlink::common::MAV_SENSOR_ORIENTATION e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:71:23: error: ‘MAV_TYPE’ is not a member of ‘mavlink::common’
 std::string to_string(mavlink::common::MAV_TYPE e);
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:71:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:62:12: note:   ‘mavlink::minimal::MAV_TYPE’
 enum class MAV_TYPE : uint8_t
            ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:72:40: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(mavlink::common::MAV_STATE e);
                                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:68:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::MAV_SENSOR_ORIENTATION)’
 std::string to_string(mavlink::common::MAV_SENSOR_ORIENTATION e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:72:23: error: ‘MAV_STATE’ is not a member of ‘mavlink::common’
 std::string to_string(mavlink::common::MAV_STATE e);
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:72:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:137:12: note:   ‘mavlink::minimal::MAV_STATE’
 enum class MAV_STATE : uint8_t
            ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:73:40: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(mavlink::common::MAV_COMPONENT e);
                                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:68:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::MAV_SENSOR_ORIENTATION)’
 std::string to_string(mavlink::common::MAV_SENSOR_ORIENTATION e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:73:23: error: ‘MAV_COMPONENT’ is not a member of ‘mavlink::common’
 std::string to_string(mavlink::common::MAV_COMPONENT e);
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:73:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:156:12: note:   ‘mavlink::minimal::MAV_COMPONENT’
 enum class MAV_COMPONENT
            ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:114:18: error: ‘MAV_TYPE’ in namespace ‘mavlink::common’ does not name a type
 mavlink::common::MAV_TYPE mav_type_from_str(const std::string &mav_type);
                  ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:24:24: error: ‘mavlink::common::MAV_AUTOPILOT’ has not been declared
 using mavlink::common::MAV_AUTOPILOT;
                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:25:24: error: ‘mavlink::common::MAV_TYPE’ has not been declared
 using mavlink::common::MAV_TYPE;
                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:26:24: error: ‘mavlink::common::MAV_STATE’ has not been declared
 using mavlink::common::MAV_STATE;
                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:27:24: error: ‘mavlink::common::MAV_COMPONENT’ has not been declared
 using mavlink::common::MAV_COMPONENT;
                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:131:23: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(MAV_AUTOPILOT e)
                       ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:80:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::LANDING_TARGET_TYPE)’
 std::string to_string(mavlink::common::LANDING_TARGET_TYPE e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:131:23: error: ‘MAV_AUTOPILOT’ was not declared in this scope
 std::string to_string(MAV_AUTOPILOT e)
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:131:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:34:12: note:   ‘mavlink::minimal::MAV_AUTOPILOT’
 enum class MAV_AUTOPILOT : uint8_t
            ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:192:23: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(MAV_TYPE e)
                       ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:80:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::LANDING_TARGET_TYPE)’
 std::string to_string(mavlink::common::LANDING_TARGET_TYPE e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:192:23: error: ‘MAV_TYPE’ was not declared in this scope
 std::string to_string(MAV_TYPE e)
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:192:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:62:12: note:   ‘mavlink::minimal::MAV_TYPE’
 enum class MAV_TYPE : uint8_t
            ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:243:21: error: ‘MAV_TYPE’ was not declared in this scope
 std::string to_name(MAV_TYPE e)
                     ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:243:21: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:62:12: note:   ‘mavlink::minimal::MAV_TYPE’
 enum class MAV_TYPE : uint8_t
            ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:244:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:280:23: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(MAV_STATE e)
                       ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:80:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::LANDING_TARGET_TYPE)’
 std::string to_string(mavlink::common::LANDING_TARGET_TYPE e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:280:23: error: ‘MAV_STATE’ was not declared in this scope
 std::string to_string(MAV_STATE e)
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:280:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:137:12: note:   ‘mavlink::minimal::MAV_STATE’
 enum class MAV_STATE : uint8_t
            ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:584:23: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(MAV_COMPONENT e)
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:431:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::GPS_FIX_TYPE)’
 std::string to_string(GPS_FIX_TYPE e)
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:584:23: error: ‘MAV_COMPONENT’ was not declared in this scope
 std::string to_string(MAV_COMPONENT e)
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:584:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:19:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:156:12: note:   ‘mavlink::minimal::MAV_COMPONENT’
 enum class MAV_COMPONENT
            ^
/root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_to_string.cpp:608:1: error: ‘MAV_TYPE’ does not name a type
 MAV_TYPE mav_type_from_str(const std::string &mav_type)
 ^
make[2]: *** [CMakeFiles/mavros.dir/src/lib/enum_to_string.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_sensor_orientation.cpp:17:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:70:40: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(mavlink::common::MAV_AUTOPILOT e);
                                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:68:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::MAV_SENSOR_ORIENTATION)’
 std::string to_string(mavlink::common::MAV_SENSOR_ORIENTATION e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:70:23: error: ‘MAV_AUTOPILOT’ is not a member of ‘mavlink::common’
 std::string to_string(mavlink::common::MAV_AUTOPILOT e);
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:70:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_sensor_orientation.cpp:17:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:34:12: note:   ‘mavlink::minimal::MAV_AUTOPILOT’
 enum class MAV_AUTOPILOT : uint8_t
            ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_sensor_orientation.cpp:17:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:71:40: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(mavlink::common::MAV_TYPE e);
                                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:68:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::MAV_SENSOR_ORIENTATION)’
 std::string to_string(mavlink::common::MAV_SENSOR_ORIENTATION e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:71:23: error: ‘MAV_TYPE’ is not a member of ‘mavlink::common’
 std::string to_string(mavlink::common::MAV_TYPE e);
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:71:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_sensor_orientation.cpp:17:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:62:12: note:   ‘mavlink::minimal::MAV_TYPE’
 enum class MAV_TYPE : uint8_t
            ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_sensor_orientation.cpp:17:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:72:40: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(mavlink::common::MAV_STATE e);
                                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:68:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::MAV_SENSOR_ORIENTATION)’
 std::string to_string(mavlink::common::MAV_SENSOR_ORIENTATION e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:72:23: error: ‘MAV_STATE’ is not a member of ‘mavlink::common’
 std::string to_string(mavlink::common::MAV_STATE e);
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:72:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_sensor_orientation.cpp:17:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:137:12: note:   ‘mavlink::minimal::MAV_STATE’
 enum class MAV_STATE : uint8_t
            ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_sensor_orientation.cpp:17:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:73:40: error: ‘std::__cxx11::string mavros::utils::to_string’ redeclared as different kind of symbol
 std::string to_string(mavlink::common::MAV_COMPONENT e);
                                        ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:68:13: note: previous declaration ‘std::__cxx11::string mavros::utils::to_string(mavlink::common::MAV_SENSOR_ORIENTATION)’
 std::string to_string(mavlink::common::MAV_SENSOR_ORIENTATION e);
             ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:73:23: error: ‘MAV_COMPONENT’ is not a member of ‘mavlink::common’
 std::string to_string(mavlink::common::MAV_COMPONENT e);
                       ^
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:73:23: note: suggested alternative:
In file included from /root/rosws/devel/include/mavlink/v2.0/common/common.hpp:2254:0,
                 from /root/rosws/src/pensa/third_party/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /root/rosws/src/pensa/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:22,
                 from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_sensor_orientation.cpp:17:
/root/rosws/devel/include/mavlink/v2.0/common/../minimal/minimal.hpp:156:12: note:   ‘mavlink::minimal::MAV_COMPONENT’
 enum class MAV_COMPONENT
            ^
In file included from /root/rosws/src/pensa/third_party/mavros/mavros/src/lib/enum_sensor_orientation.cpp:17:0:
/root/rosws/src/pensa/third_party/mavros/mavros/include/mavros/utils.h:114:18: error: ‘MAV_TYPE’ in namespace ‘mavlink::common’ does not name a type
 mavlink::common::MAV_TYPE mav_type_from_str(const std::string &mav_type);
```

**Comment by marcelino-pensa** [comment]
I have just verified that `mavros` fails to compile in `1.3.0` and on `master`

**Comment by marcelino-pensa** [comment]
Checking out to `release/kinetic/mavlink/2020.8.8-1` fixes my problem.

Before I close this issue, is `mavlink` in kinetic no longer supposed to work with `mavros`?

**Comment by vooon** [comment]
From errors i see that headers didn't generate. Did you tried to clean your workspace and then build again? `cantin clean`.

**Comment by marcelino-pensa** [comment]
Yeah, I did `catkin clean`. It was also failing in our CI environment, which builds from scratch every time...

**Comment by vooon** [comment]
Found the problem: https://github.com/mavlink/mavlink/commit/a5e3138d15461f951b701582dd23c304b5a3bc01#diff-ceacc1e2390186650146a45be8fcb691

Because of that enums changes their namespace from `mvalink::common::` to `mavlink::minimal::`.
We have to update namespaces in mavros.

**Comment by amilcarlucas** [comment]
The latest version works fine with mavros 1.4.0

**Comment by amilcarlucas** [comment]
Re-test with mavros 1.4.0 and reopen this if it does not work.
